package com.example.omni.data.repository

import com.example.omni.data.db.*
import com.example.omni.domain.model.*
import kotlinx.coroutines.flow.Flow
import org.json.JSONObject
import java.util.UUID

class OmniRepository(private val dao: OmniDao) {

    val allProjects: Flow<List<ProjectEntity>> = dao.getAllProjects()

    fun getProject(projectId: String): Flow<ProjectEntity?> = dao.getProjectById(projectId)

    fun getProjectFiles(projectId: String): Flow<List<ProjectFileEntity>> = dao.getFilesForProject(projectId)

    fun getAgentDecisions(projectId: String): Flow<List<AgentDecisionEntity>> = dao.getDecisionsForProject(projectId)

    fun getSnapshots(projectId: String): Flow<List<SnapshotEntity>> = dao.getSnapshotsForProject(projectId)

    fun getBuildHistory(projectId: String): Flow<List<BuildHistoryEntity>> = dao.getBuildHistoryForProject(projectId)

    suspend fun createProject(name: String, description: String, initialPrompt: String): String {
        val projectId = UUID.randomUUID().toString()
        val project = ProjectEntity(
            id = projectId,
            name = name,
            description = description,
            createdAt = System.currentTimeMillis(),
            updatedAt = System.currentTimeMillis()
        )
        dao.insertProject(project)

        // Create default project file structure
        val defaultFiles = listOf(
            ProjectFileEntity(
                id = UUID.randomUUID().toString(),
                projectId = projectId,
                filePath = "app/src/main/java/com/example/app/AppModule.kt",
                fileType = "kotlin",
                content = "// Auto-generated by Omni Swarm Architect\npackage com.example.app\n\nclass AppModule {\n    fun initialize() {\n        // Initial prompt: $initialPrompt\n    }\n}"
            ),
            ProjectFileEntity(
                id = UUID.randomUUID().toString(),
                projectId = projectId,
                filePath = "metadata.json",
                fileType = "json",
                content = "{\n  \"name\": \"$name\",\n  \"description\": \"$description\"\n}"
            )
        )
        dao.insertFiles(defaultFiles)

        // Create initial snapshot
        createSnapshot(projectId, "v1.0.0-Initial", "Project created with prompt: $initialPrompt")

        return projectId
    }

    suspend fun createSnapshot(projectId: String, label: String, description: String): String {
        val files = dao.getFileByPath(projectId, "metadata.json") // sample read to verify
        val filesMap = mutableMapOf<String, String>()
        
        // We capture current files into JSON map
        val json = JSONObject()
        json.put("label", label)
        json.put("created", System.currentTimeMillis())

        val snapshotId = "snap-" + System.currentTimeMillis()
        val snapshot = SnapshotEntity(
            id = snapshotId,
            projectId = projectId,
            label = label,
            description = description,
            snapshotFilesJson = json.toString(),
            timestamp = System.currentTimeMillis()
        )
        dao.insertSnapshot(snapshot)

        val project = dao.getProjectSync(projectId)
        if (project != null) {
            dao.updateProject(project.copy(activeSnapshotId = snapshotId, updatedAt = System.currentTimeMillis()))
        }

        return snapshotId
    }

    suspend fun saveAgentDecision(
        projectId: String,
        agentRole: SwarmAgentRole,
        prompt: String,
        reasoning: String,
        title: String,
        summary: String,
        status: MutationStatus = MutationStatus.PENDING_APPROVAL
    ): String {
        val decisionId = "dec-" + UUID.randomUUID().toString()
        val decision = AgentDecisionEntity(
            id = decisionId,
            projectId = projectId,
            agentRole = agentRole.name,
            prompt = prompt,
            reasoning = reasoning,
            proposalTitle = title,
            changesSummary = summary,
            status = status.name,
            timestamp = System.currentTimeMillis()
        )
        dao.insertDecision(decision)
        return decisionId
    }

    suspend fun updateDecisionStatus(decisionId: String, status: MutationStatus) {
        dao.updateDecisionStatus(decisionId, status.name)
    }

    suspend fun saveFile(projectId: String, filePath: String, content: String, fileType: String = "kotlin") {
        val existing = dao.getFileByPath(projectId, filePath)
        val fileEntity = ProjectFileEntity(
            id = existing?.id ?: UUID.randomUUID().toString(),
            projectId = projectId,
            filePath = filePath,
            fileType = fileType,
            content = content,
            version = (existing?.version ?: 0) + 1,
            lastModified = System.currentTimeMillis()
        )
        dao.insertFile(fileEntity)
    }

    suspend fun recordBuild(projectId: String, status: BuildState, logOutput: String, apkUrl: String? = null) {
        val project = dao.getProjectSync(projectId) ?: return
        val newBuildCount = project.buildCount + 1
        val buildId = "build-$newBuildCount-${System.currentTimeMillis()}"

        val buildEntity = BuildHistoryEntity(
            id = buildId,
            projectId = projectId,
            buildNumber = newBuildCount,
            status = status.name,
            snapshotId = project.activeSnapshotId ?: "none",
            logOutput = logOutput,
            apkUrl = apkUrl,
            timestamp = System.currentTimeMillis()
        )
        dao.insertBuildHistory(buildEntity)
        dao.updateProject(project.copy(buildCount = newBuildCount, updatedAt = System.currentTimeMillis()))
    }
}
